<?php

namespace ContainerIBODnKY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyInfo_ConstructorExtractorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'property_info.constructor_extractor' shared service.
     *
     * @return \Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/property-info/PropertyTypeExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/property-info/Extractor/ConstructorExtractor.php';

        return $container->privates['property_info.constructor_extractor'] = new \Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['property_info.reflection_extractor'] ??= new \Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor());
        }, 1));
    }
}
