<?php

namespace ContainerZkjvyUS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioAlice_DataLoaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'nelmio_alice.data_loader' shared service.
     *
     * @return \Nelmio\Alice\Loader\SimpleDataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/DataLoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Loader/SimpleDataLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/SimpleBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/DenormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/SimpleDenormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/ParameterBagDenormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Parameter/SimpleParameterBagDenormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FixtureBagDenormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SimpleFixtureBagDenormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/FixtureDenormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/TolerantFixtureDenormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/FixtureDenormalizerRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FlagParserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FlagParser/ElementFlagParser.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FlagParser/FlagParserRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/GeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/DoublePassGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/FixtureSetResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/FixtureSet/RemoveConflictingObjectsResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/FixtureSet/SimpleFixtureSetResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/ParameterBagResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/RemoveConflictingParametersParameterBagResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/SimpleParameterBagResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/ParameterResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/ParameterResolverRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/FixtureBagResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/Fixture/TemplateFixtureBagResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ObjectGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ObjectGenerator/CompleteObjectGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ObjectGeneratorAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Resolver/Value/ValueResolverRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/InstantiatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ValueResolverAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Instantiator/ExistingInstanceInstantiator.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Instantiator/InstantiatorResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Instantiator/InstantiatorRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/HydratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Hydrator/SimpleHydrator.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Hydrator/PropertyHydratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Hydrator/Property/SymfonyPropertyAccessorHydrator.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/CallerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/SimpleCaller.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/NamedArgumentsResolver.php';

        $a = new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\ElementFlagParser(new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\FlagParserRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.flag_parser.chainable.configurator'] ??= new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\Chainable\ConfiguratorFlagParser());
            yield 1 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.flag_parser.chainable.extend'] ??= new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\Chainable\ExtendFlagParser());
            yield 2 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.flag_parser.chainable.optional'] ??= new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\Chainable\OptionalFlagParser());
            yield 3 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.flag_parser.chainable.template'] ??= new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\Chainable\TemplateFlagParser());
            yield 4 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.flag_parser.chainable.unique'] ??= new \Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\Chainable\UniqueFlagParser());
        }, 5)));
        $b = new \Nelmio\Alice\Generator\Resolver\Value\ValueResolverRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.array_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\ArrayValueResolver());
            yield 1 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.dynamic_array_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\DynamicArrayValueResolver());
            yield 2 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.evaluated_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\EvaluatedValueResolver());
            yield 3 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.function_argument_resolver'] ?? $container->load('getNelmioAlice_Generator_Resolver_Value_Chainable_FunctionArgumentResolverService'));
            yield 4 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.fixture_property_reference_resolver'] ?? $container->load('getNelmioAlice_Generator_Resolver_Value_Chainable_FixturePropertyReferenceResolverService'));
            yield 5 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.fixture_method_call_reference_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\FixtureMethodCallReferenceResolver());
            yield 6 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.unresolved_fixture_reference_resolver'] ?? $container->load('getNelmioAlice_Generator_Resolver_Value_Chainable_UnresolvedFixtureReferenceResolverService'));
            yield 7 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.fixture_wildcard_reference_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\FixtureWildcardReferenceResolver());
            yield 8 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.list_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\ListValueResolver());
            yield 9 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.optional_value_resolver'] ?? $container->load('getNelmioAlice_Generator_Resolver_Value_Chainable_OptionalValueResolverService'));
            yield 10 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.parameter_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\ParameterValueResolver());
            yield 11 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.unique_value_resolver'] ?? $container->load('getNelmioAlice_Generator_Resolver_Value_Chainable_UniqueValueResolverService'));
            yield 12 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.value_for_current_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\ValueForCurrentValueResolver());
            yield 13 => ($container->privates['nelmio_alice.generator.resolver.value.chainable.variable_value_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Value\Chainable\VariableValueResolver());
        }, 14));

        return $container->services['nelmio_alice.data_loader'] = new \Nelmio\Alice\Loader\SimpleDataLoader(new \Nelmio\Alice\FixtureBuilder\SimpleBuilder(new \Nelmio\Alice\FixtureBuilder\Denormalizer\SimpleDenormalizer(new \Nelmio\Alice\FixtureBuilder\Denormalizer\Parameter\SimpleParameterBagDenormalizer(), new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SimpleFixtureBagDenormalizer(new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\TolerantFixtureDenormalizer(new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\FixtureDenormalizerRegistry($a, new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple_list'] ?? $container->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Chainable_SimpleListService'));
            yield 1 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.reference_range_name'] ?? $container->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Chainable_ReferenceRangeNameService'));
            yield 2 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple_range'] ?? $container->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Chainable_SimpleRangeService'));
            yield 3 => ($container->privates['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple'] ?? $container->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Chainable_SimpleService'));
        }, 4))), $a))), new \Nelmio\Alice\Generator\DoublePassGenerator(new \Nelmio\Alice\Generator\Resolver\FixtureSet\RemoveConflictingObjectsResolver(new \Nelmio\Alice\Generator\Resolver\FixtureSet\SimpleFixtureSetResolver(new \Nelmio\Alice\Generator\Resolver\Parameter\RemoveConflictingParametersParameterBagResolver(new \Nelmio\Alice\Generator\Resolver\Parameter\SimpleParameterBagResolver(new \Nelmio\Alice\Generator\Resolver\Parameter\ParameterResolverRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_alice.generator.resolver.parameter.chainable.static_parameter_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Parameter\Chainable\StaticParameterResolver());
            yield 1 => ($container->privates['nelmio_alice.generator.resolver.parameter.chainable.array_parameter_resolver'] ??= new \Nelmio\Alice\Generator\Resolver\Parameter\Chainable\ArrayParameterResolver());
            yield 2 => ($container->privates['nelmio_alice.generator.resolver.parameter.chainable.recursive_parameter_resolver'] ?? $container->load('getNelmioAlice_Generator_Resolver_Parameter_Chainable_RecursiveParameterResolverService'));
        }, 3)))), new \Nelmio\Alice\Generator\Resolver\Fixture\TemplateFixtureBagResolver())), new \Nelmio\Alice\Generator\ObjectGenerator\CompleteObjectGenerator(new \Nelmio\Alice\Generator\ObjectGenerator\SimpleObjectGenerator($b, new \Nelmio\Alice\Generator\Instantiator\ExistingInstanceInstantiator(new \Nelmio\Alice\Generator\Instantiator\InstantiatorResolver(new \Nelmio\Alice\Generator\Instantiator\InstantiatorRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_alice.generator.instantiator.chainable.no_caller_method_instantiator'] ?? $container->load('getNelmioAlice_Generator_Instantiator_Chainable_NoCallerMethodInstantiatorService'));
            yield 1 => ($container->privates['nelmio_alice.generator.instantiator.chainable.null_constructor_instantiator'] ??= new \Nelmio\Alice\Generator\Instantiator\Chainable\NullConstructorInstantiator());
            yield 2 => ($container->privates['nelmio_alice.generator.instantiator.chainable.no_method_call_instantiator'] ??= new \Nelmio\Alice\Generator\Instantiator\Chainable\NoMethodCallInstantiator());
            yield 3 => ($container->privates['nelmio_alice.generator.instantiator.chainable.static_factory_instantiator'] ?? $container->load('getNelmioAlice_Generator_Instantiator_Chainable_StaticFactoryInstantiatorService'));
            yield 4 => ($container->privates['hautelook_alice.alice.generator.instantiator.chainable.instantiated_reference_instantiator'] ?? $container->load('getHautelookAlice_Alice_Generator_Instantiator_Chainable_InstantiatedReferenceInstantiatorService'));
        }, 5)))), new \Nelmio\Alice\Generator\Hydrator\SimpleHydrator(new \Nelmio\Alice\Generator\Hydrator\Property\SymfonyPropertyAccessorHydrator(($container->privates['nelmio_alice.property_accessor.std'] ?? $container->load('getNelmioAlice_PropertyAccessor_StdService')))), new \Nelmio\Alice\Generator\Caller\SimpleCaller(new \Nelmio\Alice\Generator\Caller\CallProcessorRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_alice.generator.caller.chainable.configurator_method_call'] ??= new \Nelmio\Alice\Generator\Caller\Chainable\ConfiguratorMethodCallProcessor());
            yield 1 => ($container->privates['nelmio_alice.generator.caller.chainable.method_call_with_reference'] ??= new \Nelmio\Alice\Generator\Caller\Chainable\MethodCallWithReferenceProcessor());
            yield 2 => ($container->privates['nelmio_alice.generator.caller.chainable.optional_method_call'] ??= new \Nelmio\Alice\Generator\Caller\Chainable\OptionalMethodCallProcessor());
            yield 3 => ($container->privates['nelmio_alice.generator.caller.chainable.simple_call'] ??= new \Nelmio\Alice\Generator\Caller\Chainable\SimpleMethodCallProcessor());
        }, 4)), $b, ($container->privates['nelmio_alice.generator.named_arguments_resolver'] ??= new \Nelmio\Alice\Generator\NamedArgumentsResolver()))))));
    }
}
