<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIBODnKY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIBODnKY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIBODnKY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIBODnKY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIBODnKY\App_KernelDevDebugContainer([
    'container.build_hash' => 'IBODnKY',
    'container.build_id' => '75a42a4e',
    'container.build_time' => 1765312687,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIBODnKY');
