<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQAQefhl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQAQefhl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQAQefhl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQAQefhl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQAQefhl\App_KernelDevDebugContainer([
    'container.build_hash' => 'QAQefhl',
    'container.build_id' => '7bb276a1',
    'container.build_time' => 1765361397,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQAQefhl');
