<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZkjvyUS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZkjvyUS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZkjvyUS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZkjvyUS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZkjvyUS\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZkjvyUS',
    'container.build_id' => '5de3cba7',
    'container.build_time' => 1765317008,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZkjvyUS');
