<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc']], [], [], []],
    'app.swagger_json' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_json'], [], [['text', '/api/doc.json']], [], [], []],
    'api_usuarios_index' => [[], ['_controller' => 'App\\Controller\\UsuarioController::index'], [], [['text', '/api/v1/usuarios']], [], [], []],
    'api_usuarios_show' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/usuarios']], [], [], []],
    'api_usuarios_create' => [[], ['_controller' => 'App\\Controller\\UsuarioController::create'], [], [['text', '/api/v1/usuarios']], [], [], []],
    'api_usuarios_update' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/usuarios']], [], [], []],
    'api_usuarios_delete' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/usuarios']], [], [], []],
    'App\Controller\UsuarioController::index' => [[], ['_controller' => 'App\\Controller\\UsuarioController::index'], [], [['text', '/api/v1/usuarios']], [], [], []],
    'App\Controller\UsuarioController::show' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/usuarios']], [], [], []],
    'App\Controller\UsuarioController::create' => [[], ['_controller' => 'App\\Controller\\UsuarioController::create'], [], [['text', '/api/v1/usuarios']], [], [], []],
    'App\Controller\UsuarioController::update' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/usuarios']], [], [], []],
    'App\Controller\UsuarioController::delete' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/usuarios']], [], [], []],
];
